version: '3'

services:
  web:
    build: .
    ports:
     - "5000:5000"
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    restart: always
    env_file:
        - .env
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
