name: Packer Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Packer
      uses: hashicorp/setup-packer@v1
      with:
        packer-version: '1.10.1'

    - name: Validate Packer Template
      run: packer validate -var-file=variables.json template.json

    - name: Build Image with Packer
      run: packer build -var-file=variables.json template.json
      env:
        my_token: ${{ secrets.DIGITAL_OCEAN_API_TOKEN }}
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQLROOTPASSWORD }}
        MYSQL_DATABASE: ${{ secrets.MYSQLDATABASE }}