name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Digital Ocean container registry
      uses: docker/login-action@v1
      with:
        registry: your-registry.digitalocean.com
        username: ${{ secrets.DO_REGISTRY_USERNAME }}
        password: ${{ secrets.DO_REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build . -t your-registry.digitalocean.com/your-image:latest
        docker push your-registry.digitalocean.com/your-image:latest

    - name: Deploy using Packer
      env:
        DIGITAL_OCEAN_API_TOKEN: ${{ secrets.DIGITAL_OCEAN_API_TOKEN }}
      run: |
        packer build -var 'api_token=${{ env.DIGITAL_OCEAN_API_TOKEN }}' packer-template.json
