name: Packer Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup `packer`
      uses: hashicorp/setup-packer@main
      id: setup
      with:
        version: ${{ env.PRODUCT_VERSION }}

    - name: Validate Packer Template
      run: packer plugins install github.com/digitalocean/digitalocean

    - name: Validate Packer Template
      run: packer validate template.json

    - name: Build Image with Packer
      run: packer build template.json
      env:
        my_token: ${{ secrets.DIGITAL_OCEAN_API_TOKEN }}
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQLROOTPASSWORD }}
        MYSQL_DATABASE: ${{ secrets.MYSQLDATABASE }}